version: '3.8'
services:
  nginx:
    image: nginx:1.19.4
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:8080'
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: yapa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yapa
    ports:
      - '5433:5432'
    volumes:
      - /var/lib/postgresql/data
