version: '3.8'
services:
  nginx:
    image: nginx:1.19.4
    # depends_on:
    #   - api
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
  # api:
  #   build: ./api
  #   hostname: api
  #   command: sh -c "npm start"
  #   volumes:
  #     - ./server/src:/app/src
  #   ports:
  #     - 3000:3000
